### PR TITLE
Allow for multiple file upload at a time.

### PR DESCRIPTION
**Pull request by justacec**
This small change allows for the user to select multiple files at a time for the upload.

### CODE REVIEW

**Comment by sudobob** [comment]
Hi Justace. Have you tested/verified?

**Comment by justacec** [comment]
Tested it in a docket container based off Raspbian with Python 3.5.  (No other Python version worked)

I can share the docket file with you in a bit.

**Comment by justacec** [comment]
Here is the Dockerfile that I used:

```
FROM balenalib/raspberry-pi-python:3.5-buster

WORKDIR /home/pi/matsuura_uploader

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN ln -s /home/pi/matsuura_uploader/matsuura_uploader.service /etc/systemd/system
RUN ln -s /home/pi/matsuura_uploader/serial_sender.service /etc/systemd/system
#RUN systemctl enable matsuura_uploader
#RUN sytemctl enable serial_sender

RUN cp .env-example .env

RUN mkdir /home/pi/matsuura_uploader/uploads

RUN ln -s /home/pi/matsuura_uploader /root

EXPOSE 80/tcp
EXPOSE 1111/tcp

CMD [ "/bin/bash" ]
```

It also would not run unless I added the following line to the `.env-example` file:

```
KIOSK_USER_NAME='admin'
```

**Comment by sudobob** [comment]
Sounds good. Could you check in the docker w/some comments on what it's
for?
Also do you have time to install on the matsuura pi? Tnx

**Comment by justacec** [comment]
Check out these changes.  I believe you can follow the commands in the README now for the Docker stuff.  Let me know if it works for you.  I am still pretty new to Docker.

Also, separately, I can work to bring this code up to Python 3.10 compatibility.  I might be able to work on that tonight.  But that would be a different branch after this one is merged.

Also drag-and-drop file uploading might be a nice feature as well. ;)

**Comment by justacec** [comment]
Ok, I think that I have added the drag and drop feature.  It works well on my browser which is Safari.  It adds a dependency for the flask_dropzone library.  It might be possible in just raw JS and flask (actually I know it is), but this seemed an ok approach.

**Comment by justacec** [comment]
Ping on this PR.  Is there something that you were waiting on for a merge?  I will be heading into the shop tomorrow and thought I might be able to update it then.

**Comment by sudobob** [comment]
Is the matsuura running it now?

**Comment by justacec** [comment]
Not yet.  I was going to put it on there the other day, but people were using the machine.  I am planning on being out there tomorrow night and can put in on there and test it that way. 

I will just scp over relevant files for testing.  If things go well tomorrow then we can have a warm fuzzy to merge.

**Comment by justacec** [comment]
Great.  Now we just need to pull this down on the uploader and set the uploader branch back to Master and wipe the dust off our hands.

**Pull request merged**
